version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://saied:k8MxFNnNFDm06zkf@cluster0.e8fvdgf.mongodb.net/NinjaMern
    networks:
      - app-network

networks:
  app-network:
    driver: bridge